/*
 * This source file was generated by the Gradle 'init' task
 */
package dii.gen6.compoundsec;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Disabled;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    @Disabled("Temporarily skipping this test")
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "App should have a greeting");
    }
}
