/*
 * This source file was generated by the Gradle 'init' task
 */
package com.camt.dii.secure;

import org.junit.jupiter.api.Test;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    void appClassExists() {
        App app = new App();
        assertNotNull(app);
    }

    @Test 
    void simulateAddCardAndAccess() {
        String cardId = "card123";
        
        // First input sequence to add card and capture facade ID
        String addCardInput = String.format(
            "1\n" +          // Choose Add Card
            "%s\n" +         // Card ID
            "LOW\n" +        // Allowed floors
            "101\n",         // Allowed rooms
            cardId
        );

        // Set up input stream for first interaction
        ByteArrayInputStream inputStream = new ByteArrayInputStream(addCardInput.getBytes());
        System.setIn(inputStream);

        // Capture output to get facade ID
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintStream originalOut = System.out;
        System.setOut(new PrintStream(outputStream));

        // Run first part to add card
        try {
            App.main(new String[]{});
        } catch (Exception e) {
            // Expected to throw when input ends
        }

        // Extract facade ID from output using updated format
        String output = outputStream.toString();
        Pattern pattern = Pattern.compile("Facade ID: ([A-F0-9]+)");
        Matcher matcher = pattern.matcher(output);
        assertTrue(matcher.find(), "Facade ID should be present in output");
        String facadeId = matcher.group(1);

        // Verify the new card creation output format
        assertTrue(output.contains("=== Card Created Successfully ==="));
        assertTrue(output.contains("Card Details:"));
        assertTrue(output.contains("Allowed Floors: LOW"));
        assertTrue(output.contains("Allowed Rooms: 101"));
        assertTrue(output.contains("Please store the Facade ID securely"));

        // Second input sequence to test access
        String accessInput = String.format(
            "4\n" +          // Request Access
            "%s\n" +         // Facade ID
            "LOW\n" +        // Floor
            "101\n" +        // Room
            "6\n",          // Exit
            facadeId
        );

        // Reset input/output streams for second interaction
        inputStream = new ByteArrayInputStream(accessInput.getBytes());
        System.setIn(inputStream);
        outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));

        // Run second part to test access
        App.main(new String[]{});

        output = outputStream.toString();
        
        // Assert expected behaviors with new output format
        assertTrue(output.contains("=== Processing Access Request ==="));
        assertTrue(output.contains("Access Request Result:"));
        assertTrue(output.contains("Location: LOW floor, Room 101"));
        assertTrue(output.contains("Status: ACCESS GRANTED ✓"));
        
        // Verify error messages don't appear
        assertFalse(output.contains("Error:"), "No error messages should be present");
        
        // Check menu items are correct
        assertTrue(output.contains("=== SECURE FACILITY CLI ==="));
        assertTrue(output.contains("1. Add Card"));
        assertTrue(output.contains("4. Request Access"));
        assertTrue(output.contains("6. Exit"));

        // Restore original System.in and System.out
        System.setIn(System.in);
        System.setOut(originalOut);
    }
}
