/*
 * This source file was generated by the Gradle 'init' task
 */
package com.camt.dii.secure;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void shouldCreateAppInstance() {
        App classUnderTest = new App();
        assertNotNull("app should be created", classUnderTest);
    }
}
